### ISSUE TITLE
Test MDS edmx with VS 17.5

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework6PowerTools#118]
See https://github.com/ErikEJ/EntityFramework6PowerTools/pull/119

See https://github.com/dotnet/ef6tools/pull/41 for a fix in progress

@ajcvickers FYI

**Comment by robertmclaws** [comment]
So, I've pulled down this project and tried opening the Model1.edms file in SmokeTestNetFx on both my main system, and TWO separate clean systems I spun up on Windows 11. 

On all 3 systems, when I change SmokeTestNetCore to the following, I get a NullReferenceException when trying to open the designer.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net6.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\SqlProviderSmokeTextNetCore\Test1.cs" Link="Test1.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\SmokeTestNetFx\Model1.edmx" Link="Model1.edmx" />
    <None Include="..\SmokeTestNetFx\Model1.edmx.diagram" Link="Model1.edmx.diagram" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ErikEJ.EntityFramework.SqlServer" Version="6.6.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>

</Project>
```

I'm using the same project configuration in my own app, with the same result.

**Comment by ErikEJ** [comment]
@robertmclaws The designer only works on pure .NET Framework projects. Are you not able to open The designer in the unmodified NetFX smoke test project?

**Comment by robertmclaws** [comment]
So, EF6 works under both .NET Framework and .NET Core. The designer *used* to work just fine in this configuration under VS2022 when the provider was System.Data.SqlClient.

NOW it doesn't even work in that situation, and model updates are totally broken.

**Comment by ErikEJ** [comment]
>>  Are you not able to open The designer in the unmodified NetFX smoke test project?

Please reply. As far as I know the designer never worked with s ting else than classic .NET Framework projects

**Comment by robertmclaws** [comment]
No. It is still giving a Null Reference Exception.

**Comment by robertmclaws** [comment]
This is all that's in there, on all 3 machines:

```
    <system.data>
        <DbProviderFactories />
    </system.data>
```

Not sure if it is supposed to be different, or of Windows Update is overwriting it, or what.

**Comment by robertmclaws** [comment]
> > > Are you not able to open The designer in the unmodified NetFX smoke test project?
> 
> Please reply. As far as I know the designer never worked with s ting else than classic .NET Framework projects

Also, if you look at the project file I posted, it used to work if you listed .NET 4.8 FIRST in the list of projects to compile. I've been using it that way for the last 3+ years.

**Comment by ErikEJ** [comment]
@robertmclaws can you share a repro project, I am confused with talk about new project types and multiple target frameworks. 

The designer only works with classic. Net framework projects.

**Comment by robertmclaws** [comment]
You've said a couple times now "the designer only works with classic .NET Framework projects." As I have mentioned a few times now, that statement is not accurate. The designer works in SDK-style projects as well, but the .NET Framework (`net462, net47, net471, net472,` or `net48`) HAS to be specified as the first entry in `<TargetFrameworks />`

I know this because I've been using it this way for 3 years now.

Here's your test project [modified with changes](https://github.com/CloudNimble/EntityFramework6PowerTools/commit/07230f3fbd009e8e45f7e7e77293e9de1dc74f11) that will let the EDMX Designer be opened in "SmokeTestNetCore".

If you change the EDMX file back to `Microsoft.Data.SqlClient` and then try to open it in the designer, you you will get a NullReferenceException.

![image](https://user-images.githubusercontent.com/1657085/226223758-84e210de-f370-48f3-bf9b-e1e9c68363b8.png)

**Comment by ErikEJ** [comment]
Ok, I will have a look at this advanced scenario but still you never replied to my question:

Are you able to open the designer in the unmodified NetFX smoke test project?

**Comment by robertmclaws** [comment]
Not with Microsoft.Data.SqlClient as the provider in the EDMX file.

**Comment by ErikEJ** [comment]
I can open it just fine, so something is different on your machine(s).

And finding out what that could be seems more important to me before we move to Advanced, unsupported Configurations;

https://learn.microsoft.com/en-gb/ef/ef6/what-is-new/#ef-designer-support

What error do you get when you try to open the designer in the unmodified NetFX project?

Have you looked in the AciivityLog.xml file?

**Comment by robertmclaws** [comment]
It does not work on a clean Windows 11 system, version 25309.1000, with a clean Visual Studio 17.5.1 installed.

This seems relevant from the ActivityLog.xml:
![image](https://user-images.githubusercontent.com/1657085/226266041-ca9351b2-e525-45d4-a0b8-f0609a5c4e6c.png)

**Comment by ErikEJ** [comment]
Thanks.

I am running Windows 10 with VS 17.5.1. Do you have a Windows 10 test machine/VM available?

**Comment by robertmclaws** [comment]
No, I do not. Maybe it's a good opportunity for you to spin up a Windows 11 VM? I know that Hyper-V Quick Create has a Windows 11 Dev VM on there that might be good.

**Comment by ErikEJ** [comment]
Could you please share the error message/stack trace, thanks...

**Comment by ErikEJ** [comment]
The designer opens fine for me on a clean, new VS image from Azure with Windows 11.

**Comment by robertmclaws** [comment]
All it gives me is the message in the 2nd screenshot. I don't have a stack trace. Debugging a VS instance with another VS instance does not produce a stack trace.

What .NET Frameworks are installed on that instance?

**Comment by ErikEJ** [comment]
>> What .NET Frameworks are installed on that instance?

Is there not only one? 

Maybe you can share your machine.config file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config (privately if you prefer) and I can do a compare

**Comment by robertmclaws** [comment]
There are definitely more than one. 
![image](https://user-images.githubusercontent.com/1657085/226288889-a16ae180-14ab-430c-80b6-e1b5ef726622.png)

My machine.config in `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config` is identical to machine.config.default.

**Comment by ErikEJ** [comment]
Ah, you mean targeting packs for Visual Studio. Let me check

**Comment by ErikEJ** [comment]
@robertmclaws I really appreciate all your effort, but sadly I have now tried on two machines and am unable to repro. Really annoying.

A Teams meeting perhaps, if you are interested in taking this further?

**Comment by robertmclaws** [comment]
Sure! Want to DM me on Twitter and we'll set it up?

**Comment by robertmclaws** [comment]
Question, are you opening from my repo or yours?

**Comment by ErikEJ** [comment]
I am always opening from my unmodified repo

**Comment by robertmclaws** [comment]
It still reproduces the issue in supported configurations.

**Comment by ErikEJ** [comment]
@robertmclaws Yes, for you, I know, so let us focus on that.

@ryanbrandenburg @CZEMacLeod @jasonmalinowski  @ajcvickers @bricelam 

- are any of you able to open the EDMX designer using VS 17.5 or later in the project here:
https://github.com/ErikEJ/EntityFramework6PowerTools/tree/community/test/SmokeTestNetFx

**Comment by ajcvickers** [comment]
@ErikEJ I get a null ref exception with VS Community 17.5.3 and VS Enterprise 17.6.0 Preview 2:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/1430078/227205441-c7f0b98c-600b-48cd-b821-8a77df29eecc.png">

**Comment by ErikEJ** [comment]
@ajcvickers  Thanks for confirming.

**Comment by CZEMacLeod** [comment]
@ErikEJ Just checked with VS Pro 17.5.2 then 17.5.3 after updating
Same thing on 17.5.2 but it worked on 17.5.3!
![image](https://user-images.githubusercontent.com/7670113/227235973-801a22dd-b21c-4b29-9ec7-f8fec47a25b9.png)
![image](https://user-images.githubusercontent.com/7670113/227239382-9afe54d9-298c-4e4d-a7d5-0097e68d3883.png)

Literally did nothing different. Hit the update on close notification. Closed VS. Updated. Reopened VS and the solution as before, then just double clicked the Model1.edmx (as before).
Was expecting the same result but **no**. Sorry to muddy the waters here!
Only thing I can think of is if I tried to open it too 'early' (before package restore completed maybe?) the first time, and the second time it had had time to complete the loading and restore.

**Comment by ErikEJ** [comment]
@CZEMacLeod I would imagine a package restore and background build would be needed, as the provider is enabled via app config in the test app itself. Much appreciate your time!

**Comment by ErikEJ** [comment]
@ajcvickers @robertmclaws Are you able to get the latest community branch commits and give it another try, I just made some small adjustments.

**Comment by robertmclaws** [comment]
I'm glad we're starting to make progress, and that more than 1 person has validated a) my issue, and b) my use case.

I just want to point out that you would have found this problem sooner if you had pulled down my branch, which would not have had compiled binaries in the bin folder, and then tried opening the model before compiling.

**Comment by ErikEJ** [comment]
@robertmclaws So are you able to open The designer now??

**Comment by ErikEJ** [comment]
@ryanbrandenburg Maybe the error message could be improved here?

**Comment by robertmclaws** [comment]
Put of the 4 machines, there is still one that refuses to open the model from your branch. That is my main development machine. Now I just get this error.

<img src="https://user-images.githubusercontent.com/1657085/227782042-8c8512c1-ec50-45a1-aaee-c3a7e4bf3779.png">

**Comment by ErikEJ** [comment]
@robertmclaws Assume you got the 4th machine running then?

**Comment by robertmclaws** [comment]
Hey @ErikEJ @ajcvickers, I'm still not able to open a model with EF 6.5.1 in the designer (I'm aware this has been mentioned as not supported but I think it can be resolved easily) I was finally able to get a stack trace from VS 17.11 Preview 5.

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Entity.Design.VersioningFacade.LegacyProviderWrapper.LegacyDbProviderServicesWrapper.GetDbProviderManifest(String manifestToken)
   at System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifest(String manifestToken)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Loader.InitializeProviderManifest(Action`3 addError)
   at System.Data.Entity.Core.SchemaObjectModel.Schema.HandleAttribute(XmlReader reader)
   at System.Data.Entity.Core.SchemaObjectModel.SchemaElement.ParseAttribute(XmlReader reader)
   at System.Data.Entity.Core.SchemaObjectModel.SchemaElement.Parse(XmlReader reader)
   at System.Data.Entity.Core.SchemaObjectModel.Schema.HandleTopLevelSchemaElement(XmlReader reader)
   at System.Data.Entity.Core.SchemaObjectModel.Schema.InternalParse(XmlReader sourceReader, String sourceLocation)
   at System.Data.Entity.Core.SchemaObjectModel.Schema.Parse(XmlReader sourceReader, String sourceLocation)
   at System.Data.Entity.Core.SchemaObjectModel.SchemaManager.ParseAndValidate(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths, SchemaDataModelOption dataModel, AttributeValueNotification providerNotification, AttributeValueNotification providerManifestTokenNotification, ProviderManifestNeeded providerManifestNeeded, IList`1& schemaCollection)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Loader.LoadItems(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Init(IEnumerable`1 xmlReaders, IEnumerable`1 filePaths, Boolean throwOnError, IDbDependencyResolver resolver, DbProviderManifest& providerManifest, DbProviderFactory& providerFactory, String& providerInvariantName, String& providerManifestToken, Memoizer`2& cachedCTypeFunction)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection..ctor(IEnumerable`1 xmlReaders, ReadOnlyCollection`1 filePaths, IDbDependencyResolver resolver, IList`1& errors)
   at System.Data.Entity.Core.Metadata.Edm.StoreItemCollection.Create(IEnumerable`1 xmlReaders, ReadOnlyCollection`1 filePaths, IDbDependencyResolver resolver, IList`1& errors)
   at Microsoft.Data.Entity.Design.Model.Validation.RuntimeMetadataValidator.ValidateStoreModel(EntityDesignArtifact designArtifact)
   at Microsoft.Data.Entity.Design.Model.Validation.RuntimeMetadataValidator.ValidateArtifactSet(EFArtifactSet artifactSet, Boolean forceValidation, Boolean validateMsl, Boolean runViewGen)
   at Microsoft.Data.Entity.Design.Model.EntityDesignArtifact.DetermineIfArtifactIsStructurallySafe()
   at Microsoft.Data.Entity.Design.Model.EntityDesignArtifact.DetermineIfArtifactIsDesignerSafe()
   at Microsoft.Data.Entity.Design.VisualStudio.Model.VSArtifact.DetermineIfArtifactIsDesignerSafe()
   at Microsoft.Data.Entity.Design.Model.EFArtifact.get_IsDesignerSafe()
   at Microsoft.Data.Entity.Design.EntityDesigner.CustomSerializer.EntityModelToDslModelTranslatorStrategy.TranslateModelToDslModel(EFObject modelElement, Partition partition)
   at Microsoft.Data.Entity.Design.EntityDesigner.MicrosoftDataEntityDesignSerializationHelper.LoadModel(SerializationResult serializationResult, Partition partition, String fileName, ISchemaResolver schemaResolver, ValidationController validationController, ISerializerLocator serializerLocator)
   at Microsoft.Data.Entity.Design.EntityDesigner.MicrosoftDataEntityDesignSerializationHelper.LoadModelAndDiagram(SerializationResult serializationResult, Partition modelPartition, String modelFileName, Partition diagramPartition, String diagramFileName, ISchemaResolver schemaResolver, ValidationController validationController, ISerializerLocator serializerLocator)
   at Microsoft.Data.Entity.Design.Package.MicrosoftDataEntityDesignDocDataBase.Load(String fileName, Boolean isReload)
   at Microsoft.VisualStudio.Modeling.Shell.ModelingDocData.LoadDocData(String fileName, Boolean isReload)
   at Microsoft.Data.Entity.Design.Package.MicrosoftDataEntityDesignDocData.LoadDocData(String fileName, Boolean isReload)
   at Microsoft.VisualStudio.Modeling.Shell.DocData.ReloadDocDataWorker(UInt32 flags)
   at Microsoft.VisualStudio.Modeling.Shell.DocData.OnFileChangeTimerTick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
I'm happy to try to fix this if there are instructions anywhere on how to set up a dev environment to use a locally-compiled version.

**Comment by ErikEJ** [comment]
@robertmclaws For issues and advice regading the VS designer, use this repo: https://github.com/dotnet/ef6tools
