### ISSUE TITLE
'Unable to cast object of type 'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.'

### ISSUE THREAD

**Issue by jfrank14** [ErikEJ/EntityFramework6PowerTools#127]
I'm using EF6 and .NET Framework 4.8, and I'm trying to upgrade to use the new provider, for the usual reasons.

When I make my first EF query, I get the above error, even though I've followed the configuration instructions completely, as far as I can see.

**Comment by jfrank14** [comment]
The stack trace, if useful, is:

```
   at System.Data.SqlClient.SqlCommand.set_DbConnection(DbConnection value)
   at System.Data.Entity.Core.Common.Utils.CommandHelper.SetStoreProviderCommandState(EntityCommand entityCommand, EntityTransaction entityTransaction, DbCommand storeProviderCommand)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.PrepareEntityCommandBeforeExecution(EntityCommand entityCommand)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at {the place in the stack where I'm trying to make the EF call}
```

**Comment by ErikEJ** [comment]
Something somewhere is still configured to use the old ado.net provider.

**Comment by jfrank14** [comment]
Any idea how I can find that something?

**Comment by ErikEJ** [comment]
Carefully read the readme? Or share a repro. 

And inspect your dependencies.

**Comment by ErikEJ** [comment]
Any news?

**Comment by jfrank14** [comment]
I think I found the problem in the EDMX file itself
`<Schema Namespace="Data" Provider="Microsoft.Data.SqlClient" ProviderManifestToken="2012" Alias="Self" xmlns:store="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator" xmlns:customannotation="http://schemas.microsoft.com/ado/2013/11/edm/customannotation" xmlns="http://schemas.microsoft.com/ado/2009/11/edm/ssdl">`

It took me a while to think to look in a file that I never use directly.

**Comment by ErikEJ** [comment]
As documented 😉
