### ISSUE TITLE
Generate Views does not work if model uses HasIndex (new API in 6.2)

### ISSUE THREAD

**Issue by AlexKichkailo** [ErikEJ/EntityFramework6PowerTools#22]
Below is a simple project to reproduce the problem. Note that it uses EF 6.2

[EFToolsHasIndexIssue.zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/1509397/EFToolsHasIndexIssue.zip)

The error message in the Output window is 

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'System.Data.Entity.ModelConfiguration.Configuration.IndexConfiguration System.Data.Entity.ModelConfiguration.EntityTypeConfiguration`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,!!0>>)'.
   at EFToolsHasIndexIssue.BooksDbContext.OnModelCreating(DbModelBuilder modelBuilder)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModelBuilder()
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
   at System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at CallSite.Target(Closure , CallSite , Object , String , BindingFlags , Object , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at Microsoft.DbContextPackage.DbContextPackage.GetObjectContext(Object context)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Microsoft.DbContextPackage.Handlers.OptimizeContextHandler.OptimizeContext(Object context)` 

**Product Version:**
Microsoft Visual Studio Enterprise 2017 
Version 15.4.5
VisualStudio.15.Release/15.4.5+27004.2010
Microsoft .NET Framework
Version 4.7.02558

Installed Version: Enterprise

**Comment by AlexKichkailo** [comment]
As a workaround replace EntityFramework.dll and EntityFramework.SqlServer.dll in C:/Program Files (x86)/Microsoft Visual Studio/2017/<VSEdition>/Common7/IDE/ with the EntityFramework 6.2.0 dlls

**Comment by ErikEJ** [comment]
I think the missing piece is an update of the EF 6 Tools in Visual Studio...

**Comment by AlexKichkailo** [comment]
That's interesting. I have the latest version of VS 2017. It's updated today. I reinstalled EF Tools via Programs and Features and can confirm that EF Tools in VS 2017 as of today still use EF 6.1.40302.

Why not to use the EF library referenced in the current active project? I've already implemented this change and can send a PR if it makes sense.

**Comment by ErikEJ** [comment]
I would like to see that change/PR for sure.

As you can see in the blog post here, the EF 6.2 tools are delayed in VS 2017: https://blogs.msdn.microsoft.com/dotnet/2017/10/26/entity-framework-6-2-runtime-released/

**Comment by AlexKichkailo** [comment]
[Here ](https://github.com/ErikEJ/EntityFramework6PowerTools/pull/23)is a PR

**Comment by ErikEJ** [comment]
External issue (must wait for proper EF 6.2 tooling)
